FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY src/HMS.Web/HMS.Web.csproj ./HMS.Web/
RUN dotnet restore ./HMS.Web/

COPY src/HMS.Web/ ./HMS.Web/
RUN dotnet publish ./HMS.Web/ -c Release -o /app/publish

# Runtime image
FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app

COPY --from=build /app/publish .

RUN ls -la /app

EXPOSE 8080

ENTRYPOINT ["dotnet", "HMS.Web.dll"]